#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
INPUT_FILE="${ROOT_DIR}/internal/api/openapi.yaml"
OUTPUT_FILE="${ROOT_DIR}/internal/api/openapi.md"
TMP_FILE="${OUTPUT_FILE}.tmp"

if [ ! -f "${INPUT_FILE}" ]; then
  echo "missing input file: ${INPUT_FILE}" >&2
  exit 1
fi

{
  cat <<'HEADER'
# Statocyst OpenAPI Companion

Machine-readable source of truth:
- Canonical spec: `/openapi.yaml`
- Markdown companion: `/openapi.md`

This markdown file is generated from `internal/api/openapi.yaml` for agent ingestion.
Do not edit this file directly.

## OpenAPI YAML

```yaml
HEADER
  cat "${INPUT_FILE}"
  cat <<'FOOTER'
```
FOOTER
} > "${TMP_FILE}"

mv "${TMP_FILE}" "${OUTPUT_FILE}"
echo "generated ${OUTPUT_FILE}"
